//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhModule.Community.Pathing {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BhModule.Community.Pathing.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        internal static string CategoryContextMenuStrip_SearchMarker {
            get {
                return ResourceManager.GetString("CategoryContextMenuStrip_SearchMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Categories Are Hidden 的當地語系化字串。
        /// </summary>
        internal static string CategoryContextMenuStrip_ShowAllSkippedCategories {
            get {
                return ResourceManager.GetString("CategoryContextMenuStrip_ShowAllSkippedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Donate 的當地語系化字串。
        /// </summary>
        internal static string DonateHero_DonateButton {
            get {
                return ResourceManager.GetString("DonateHero_DonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Consider  helping  Freesnöw  with  server  expenses: 的當地語系化字串。
        /// </summary>
        internal static string DonateHero_DonateDesc {
            get {
                return ResourceManager.GetString("DonateHero_DonateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pathing 的當地語系化字串。
        /// </summary>
        internal static string General_UiName {
            get {
                return ResourceManager.GetString("General_UiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Categories hidden because they are for markers on a different map.
        ///
        ///Click to view them or you can disable this filter by toggling:
        ///Pathing Module Settings &gt; Marker Options &gt; {0}. 的當地語系化字串。
        /// </summary>
        internal static string Info_HiddenCategories {
            get {
                return ResourceManager.GetString("Info_HiddenCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Approx. {0:n0} downloads per day 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_BasicTooltipText {
            get {
                return ResourceManager.GetString("MarkerPackHero_BasicTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_DeleteButton {
            get {
                return ResourceManager.GetString("MarkerPackHero_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_Download {
            get {
                return ResourceManager.GetString("MarkerPackHero_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading... 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_IsDownloading {
            get {
                return ResourceManager.GetString("MarkerPackHero_IsDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading... 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_IsLoading {
            get {
                return ResourceManager.GetString("MarkerPackHero_IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updated {0} 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_LastUpdateStr {
            get {
                return ResourceManager.GetString("MarkerPackHero_LastUpdateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_Update {
            get {
                return ResourceManager.GetString("MarkerPackHero_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Up to Date 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackHero_UpToDate {
            get {
                return ResourceManager.GetString("MarkerPackHero_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Requesting latest list of marker packs... 的當地語系化字串。
        /// </summary>
        internal static string MarkerPackRepo_Progress {
            get {
                return ResourceManager.GetString("MarkerPackRepo_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_Always {
            get {
                return ResourceManager.GetString("ModuleSettings_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_Default {
            get {
                return ResourceManager.GetString("ModuleSettings_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_Never {
            get {
                return ResourceManager.GetString("ModuleSettings_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never Display 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_NeverDisplay {
            get {
                return ResourceManager.GetString("ModuleSettings_NeverDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only When Interacted With 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_OnlyWhenInteractedWith {
            get {
                return ResourceManager.GetString("ModuleSettings_OnlyWhenInteractedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Without Background 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_WithoutBackground {
            get {
                return ResourceManager.GetString("ModuleSettings_WithoutBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All Markers 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_AllMarkers {
            get {
                return ResourceManager.GetString("PackInitiator_AllMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always Load 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_AlwaysLoad {
            get {
                return ResourceManager.GetString("PackInitiator_AlwaysLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Pack 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_DeletePack {
            get {
                return ResourceManager.GetString("PackInitiator_DeletePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_DownloadMarkerPacks {
            get {
                return ResourceManager.GetString("PackInitiator_DownloadMarkerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading marker packs... 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadingIndicator1 {
            get {
                return ResourceManager.GetString("PackInitiator_LoadingIndicator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading {0}... 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadingIndicator2 {
            get {
                return ResourceManager.GetString("PackInitiator_LoadingIndicator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finalizing marker collection... 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadingIndicator3 {
            get {
                return ResourceManager.GetString("PackInitiator_LoadingIndicator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading scripts... 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadingIndicator4 {
            get {
                return ResourceManager.GetString("PackInitiator_LoadingIndicator4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load Marker Pack 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadManually {
            get {
                return ResourceManager.GetString("PackInitiator_LoadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loaded in {0} milliseconds 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_LoadManuallyIsLoaded {
            get {
                return ResourceManager.GetString("PackInitiator_LoadManuallyIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_ManagePacks {
            get {
                return ResourceManager.GetString("PackInitiator_ManagePacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reload Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_ReloadMarkers {
            get {
                return ResourceManager.GetString("PackInitiator_ReloadMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unload Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string PackInitiator_UnloadMarkers {
            get {
                return ResourceManager.GetString("PackInitiator_UnloadMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scripts 的當地語系化字串。
        /// </summary>
        internal static string PathingGlobal_Menu {
            get {
                return ResourceManager.GetString("PathingGlobal_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pathing Module Settings 的當地語系化字串。
        /// </summary>
        internal static string PathingModule_OpenSettings {
            get {
                return ResourceManager.GetString("PathingModule_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Script Console 的當地語系化字串。
        /// </summary>
        internal static string PathingModule_ScriptConsole {
            get {
                return ResourceManager.GetString("PathingModule_ScriptConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Categories 的當地語系化字串。
        /// </summary>
        internal static string Repo_Categories {
            get {
                return ResourceManager.GetString("Repo_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        internal static string Repo_Download {
            get {
                return ResourceManager.GetString("Repo_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Info 的當地語系化字串。
        /// </summary>
        internal static string Repo_Info {
            get {
                return ResourceManager.GetString("Repo_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search markers or insert path... 的當地語系化字串。
        /// </summary>
        internal static string Setting_CategoryTreeSearchBox {
            get {
                return ResourceManager.GetString("Setting_CategoryTreeSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right click on categories for options. 的當地語系化字串。
        /// </summary>
        internal static string Setting_HelpTextLabel {
            get {
                return ResourceManager.GetString("Setting_HelpTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Updated 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeepUpdatedCheckbox {
            get {
                return ResourceManager.GetString("Setting_KeepUpdatedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If checked, new pack versions will be automatically downloaded on launch. 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeepUpdatedCheckboxDesc {
            get {
                return ResourceManager.GetString("Setting_KeepUpdatedCheckboxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reload Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeyBindReloadMarkerPacks {
            get {
                return ResourceManager.GetString("Setting_KeyBindReloadMarkerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle Markers on Map 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeyBindToggleMapPathables {
            get {
                return ResourceManager.GetString("Setting_KeyBindToggleMapPathables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle Markers 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeyBindTogglePathables {
            get {
                return ResourceManager.GetString("Setting_KeyBindTogglePathables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle Markers in World 的當地語系化字串。
        /// </summary>
        internal static string Setting_KeyBindToggleWorldPathables {
            get {
                return ResourceManager.GetString("Setting_KeyBindToggleWorldPathables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity on Fullscreen Map 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapDrawOpacity {
            get {
                return ResourceManager.GetString("Setting_MapDrawOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fade Trail Segments Which Are High Above or Below 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapFadeVerticallyDistantTrailSegments {
            get {
                return ResourceManager.GetString("Setting_MapFadeVerticallyDistantTrailSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Markers on Maps 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapPathablesEnabled {
            get {
                return ResourceManager.GetString("Setting_MapPathablesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Above/Below Indicators 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowAboveBelowIndicators {
            get {
                return ResourceManager.GetString("Setting_MapShowAboveBelowIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Markers on the Minimap 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowMarkersOnCompass {
            get {
                return ResourceManager.GetString("Setting_MapShowMarkersOnCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Markers on Fullscreen Map 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowMarkersOnFullscreen {
            get {
                return ResourceManager.GetString("Setting_MapShowMarkersOnFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Tooltips on Map 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowTooltip {
            get {
                return ResourceManager.GetString("Setting_MapShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, tooltips will be shown on the map when the cursor is over a marker. 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowTooltipDesc {
            get {
                return ResourceManager.GetString("Setting_MapShowTooltipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Trails on the Minimap 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowTrailsOnCompass {
            get {
                return ResourceManager.GetString("Setting_MapShowTrailsOnCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Trails on Fullscreen Map 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapShowTrailsOnFullscreen {
            get {
                return ResourceManager.GetString("Setting_MapShowTrailsOnFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Trail Width on Maps 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapTrailWidth {
            get {
                return ResourceManager.GetString("Setting_MapTrailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The thickness of trails shown on the map. 的當地語系化字串。
        /// </summary>
        internal static string Setting_MapTrailWidthDesc {
            get {
                return ResourceManager.GetString("Setting_MapTrailWidthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity on the Minimap 的當地語系化字串。
        /// </summary>
        internal static string Setting_MiniMapDrawOpacity {
            get {
                return ResourceManager.GetString("Setting_MiniMapDrawOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Map Only 的當地語系化字串。
        /// </summary>
        internal static string Setting_OnlyShowCurrentMap {
            get {
                return ResourceManager.GetString("Setting_OnlyShowCurrentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If checked, only marker packs with marker or trails for the current map will be shown. 的當地語系化字串。
        /// </summary>
        internal static string Setting_OnlyShowCurrentMapDesc {
            get {
                return ResourceManager.GetString("Setting_OnlyShowCurrentMapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow Markers to Show Interact Gear On-Screen 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowInteractIcon {
            get {
                return ResourceManager.GetString("Setting_PackAllowInteractIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, interactable markers will show a small gear icon on-screen to show what the interaction will do. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowInteractIconDesc {
            get {
                return ResourceManager.GetString("Setting_PackAllowInteractIconDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow Markers to Animate 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowMarkersToAnimate {
            get {
                return ResourceManager.GetString("Setting_PackAllowMarkersToAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allows animations such as &apos;bounce&apos; and trail movements. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowMarkersToAnimateDesc {
            get {
                return ResourceManager.GetString("Setting_PackAllowMarkersToAnimateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow Markers to Automatically Hide 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowMarkersToAutomaticallyHide {
            get {
                return ResourceManager.GetString("Setting_PackAllowMarkersToAutomaticallyHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, markers and trails may hide themselves as a result of interactions, API data, current festival, etc.  Disabling this feature forces all markers on the map to be shown. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackAllowMarkersToAutomaticallyHideDesc {
            get {
                return ResourceManager.GetString("Setting_PackAllowMarkersToAutomaticallyHideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Smart Categories 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackEnableSmartCategoryFilter {
            get {
                return ResourceManager.GetString("Setting_PackEnableSmartCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If a category doesn&apos;t contain markers or trails relevant to the current map, the category is hidden. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackEnableSmartCategoryFilterDesc {
            get {
                return ResourceManager.GetString("Setting_PackEnableSmartCategoryFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fade Markers Between Character and Camera 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadeMarkersBetweenCharacterAndCamera {
            get {
                return ResourceManager.GetString("Setting_PackFadeMarkersBetweenCharacterAndCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, markers will be drawn with less opacity if they are directly between your character and the camera to avoid obscuring your vision. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadeMarkersBetweenCharacterAndCameraDesc {
            get {
                return ResourceManager.GetString("Setting_PackFadeMarkersBetweenCharacterAndCameraDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fade Markers and Trails While in Combat 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadePathablesDuringCombat {
            get {
                return ResourceManager.GetString("Setting_PackFadePathablesDuringCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, markers and trails will be hidden while you&apos;re in combat to avoid obscuring the fight. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadePathablesDuringCombatDesc {
            get {
                return ResourceManager.GetString("Setting_PackFadePathablesDuringCombatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fade Trails Around Character 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadeTrailsAroundCharacter {
            get {
                return ResourceManager.GetString("Setting_PackFadeTrailsAroundCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, trails will be faded out around your character to make it easier to see your character. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackFadeTrailsAroundCharacterDesc {
            get {
                return ResourceManager.GetString("Setting_PackFadeTrailsAroundCharacterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Marker Info Display Mode 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackInfoDisplayMode {
            get {
                return ResourceManager.GetString("Setting_PackInfoDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default - Popups with extra info will show when you are near certain markers.
        ///
        ///Without Background - Extra info will show when you are near certain markers, but there won&apos;t be a background behind the text.
        ///
        ///Never Display - Markers will not show popup info text on your screen. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackInfoDisplayModeDesc {
            get {
                return ResourceManager.GetString("Setting_PackInfoDisplayModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow Markers to Set Clipboard 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMarkerConsentToClipboard {
            get {
                return ResourceManager.GetString("Setting_PackMarkerConsentToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Some markers support copying text to your clipboard (such as waypoints or build templates).
        ///
        ///Always (Default) - Markers can always update your clipboard.  This can occur on interact ({0}) or automatically when you walk in range of the marker.
        ///
        ///Only When Interacted With - Markers can update your clipboard ONLY when interacted ({0}) with directly.  Markers configured as automatic will require interaction.
        ///
        ///Never - Markers can never update your clipboard. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMarkerConsentToClipboardDescription {
            get {
                return ResourceManager.GetString("Setting_PackMarkerConsentToClipboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Marker Scale 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMarkerScale {
            get {
                return ResourceManager.GetString("Setting_PackMarkerScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modifies the size of markers in the world. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMarkerScaleDesc {
            get {
                return ResourceManager.GetString("Setting_PackMarkerScaleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Opacity Override 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMaxOpacityOverride {
            get {
                return ResourceManager.GetString("Setting_PackMaxOpacityOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Trail Animation Speed 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMaxTrailAnimationSpeed {
            get {
                return ResourceManager.GetString("Setting_PackMaxTrailAnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max View Distance 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackMaxViewDistance {
            get {
                return ResourceManager.GetString("Setting_PackMaxViewDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search marker packs... 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackRepoSearchBox {
            get {
                return ResourceManager.GetString("Setting_PackRepoSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Categories From All Maps 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowCategoriesFromAllMaps {
            get {
                return ResourceManager.GetString("Setting_PackShowCategoriesFromAllMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Temporarily Show Ghost Markers 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowHiddenMarkersReducedOpacity {
            get {
                return ResourceManager.GetString("Setting_PackShowHiddenMarkersReducedOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shows hidden markers with a reduced opacity allowing you to unhide them.  This setting automatically disables on startup. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowHiddenMarkersReducedOpacityDesc {
            get {
                return ResourceManager.GetString("Setting_PackShowHiddenMarkersReducedOpacityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Tooltips for Achievements 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowTooltipsOnAchievements {
            get {
                return ResourceManager.GetString("Setting_PackShowTooltipsOnAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning: This can cause performance issues when browsing categories. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowTooltipsOnAchievementsDesc {
            get {
                return ResourceManager.GetString("Setting_PackShowTooltipsOnAchievementsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Indicate When Categories Are Hidden 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowWhenCategoriesAreFiltered {
            get {
                return ResourceManager.GetString("Setting_PackShowWhenCategoriesAreFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shows a note at the bottom of the menu indicating if categories have been hidden.  Clicking the note will show the hidden categories temporarily. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackShowWhenCategoriesAreFilteredDesc {
            get {
                return ResourceManager.GetString("Setting_PackShowWhenCategoriesAreFilteredDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the game to load the marker packs. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PacksNotInitializedLabel {
            get {
                return ResourceManager.GetString("Setting_PacksNotInitializedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No marker packs have been loaded. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PacksNotLoadedLabel {
            get {
                return ResourceManager.GetString("Setting_PacksNotLoadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Truncate Long Category Names 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackTruncateLongCategoryNames {
            get {
                return ResourceManager.GetString("Setting_PackTruncateLongCategoryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shortens long category names so that more nested menus can be shown on screen. 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackTruncateLongCategoryNamesDesc {
            get {
                return ResourceManager.GetString("Setting_PackTruncateLongCategoryNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Markers in World 的當地語系化字串。
        /// </summary>
        internal static string Setting_PackWorldPathablesEnabled {
            get {
                return ResourceManager.GetString("Setting_PackWorldPathablesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Script Console 的當地語系化字串。
        /// </summary>
        internal static string Setting_ScriptsConsoleEnabled {
            get {
                return ResourceManager.GetString("Setting_ScriptsConsoleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, the Script Console can be accessed from the Pathing module menu to debug scripts. 的當地語系化字串。
        /// </summary>
        internal static string Setting_ScriptsConsoleEnabledDesc {
            get {
                return ResourceManager.GetString("Setting_ScriptsConsoleEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Lua Scripts 的當地語系化字串。
        /// </summary>
        internal static string Setting_ScriptsEnabled {
            get {
                return ResourceManager.GetString("Setting_ScriptsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, marker packs may load Lua scripts to provide custom functionality. 的當地語系化字串。
        /// </summary>
        internal static string Setting_ScriptsEnabledDesc {
            get {
                return ResourceManager.GetString("Setting_ScriptsEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No categories found... 的當地語系化字串。
        /// </summary>
        internal static string Setting_SearchStatusLabel {
            get {
                return ResourceManager.GetString("Setting_SearchStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download  Marker  Packs 的當地語系化字串。
        /// </summary>
        internal static string SettingHero_OpenMarkerPacks {
            get {
                return ResourceManager.GetString("SettingHero_OpenMarkerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open  Settings 的當地語系化字串。
        /// </summary>
        internal static string SettingHero_OpenSettings {
            get {
                return ResourceManager.GetString("SettingHero_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open  Setup  Guide 的當地語系化字串。
        /// </summary>
        internal static string SettingHero_OpenSetupGuide {
            get {
                return ResourceManager.GetString("SettingHero_OpenSetupGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All Markers 的當地語系化字串。
        /// </summary>
        internal static string Tree_AllMarkers {
            get {
                return ResourceManager.GetString("Tree_AllMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} hidden (click to show) 的當地語系化字串。
        /// </summary>
        internal static string Tree_ShowAllSkippedCategories {
            get {
                return ResourceManager.GetString("Tree_ShowAllSkippedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category Explorer 的當地語系化字串。
        /// </summary>
        internal static string Window_CategoryTreeTab {
            get {
                return ResourceManager.GetString("Window_CategoryTreeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Marker Packs 的當地語系化字串。
        /// </summary>
        internal static string Window_DownloadMarkerPacks {
            get {
                return ResourceManager.GetString("Window_DownloadMarkerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Key Bindings 的當地語系化字串。
        /// </summary>
        internal static string Window_KeyBindSettingsTab {
            get {
                return ResourceManager.GetString("Window_KeyBindSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Marker Options 的當地語系化字串。
        /// </summary>
        internal static string Window_MainSettingsTab {
            get {
                return ResourceManager.GetString("Window_MainSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map Options 的當地語系化字串。
        /// </summary>
        internal static string Window_MapSettingsTab {
            get {
                return ResourceManager.GetString("Window_MapSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Script Options 的當地語系化字串。
        /// </summary>
        internal static string Window_ScriptSettingsTab {
            get {
                return ResourceManager.GetString("Window_ScriptSettingsTab", resourceCulture);
            }
        }
    }
}
